services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000" # 호스트 포트 5000 -> 컨테이너 포트 5000
    environment:
      - FLASK_ENV=development
      - FIREBASE_PROJECT_ID=your-firebase-project-id
      - FIREBASE_API_KEY=your-firebase-api-key
    volumes:
      - .:/flask # 로컬 디렉토리를 컨테이너에 마운트
