apiVersion: apps/v1
kind: Deployment
metadata:
  name: handoc-flask-deployment
  labels:
    app: handoc-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: handoc-flask
  template:
    metadata:
      labels:
        app: handoc-flask
    spec:
      containers:
      - name: handoc-flask
        image: 2jay0/handoc-flask:latest
        ports:
        - containerPort: 5000
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MODEL_PATH
          value: "/flask/model/4c_b5ns_1.5e_640_ext_15ep_best_fold0.pth"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: handoc-flask-service
  labels:
    app: handoc-flask
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: handoc-flask
