apiVersion: apps/v1
kind: Deployment
metadata:
  name: handoc-flask-deployment
  labels:
    app: handoc-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: handoc-flask
  template:
    metadata:
      labels:
        app: handoc-flask
    spec:
      containers:
      - name: handoc-flask
        image: 2jay0/handoc-flask:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: model-volume
          mountPath: /flask/models
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MODEL_PATH
          value: "/flask/models/4c_b5ns_1.5e_640_ext_15ep_best_fold0.pth"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: model-volume
        hostPath:
          path: /flask/models
          type: DirectoryOrCreate