apiVersion: apps/v1
kind: Deployment
metadata:
  name: handoc-flask-deployment
  labels:
    app: handoc-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: handoc-flask
  template:
    metadata:
      labels:
        app: handoc-flask
    spec:
      containers:
      - name: handoc-flask
        image: 2jay0/handoc-flask:latest
        ports:
        - containerPort: 5000
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MODEL_PATH
          value: "/app/model/4c_b5ns_1.5e_640_ext_15ep_best_fold0.pth"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---            
apiVersion: v1
kind: Service
metadata:
  name: handoc-flask-service
  labels:
    app: handoc-flask
spec:
  type: NodePort
  selector:
    app: handoc-flask  # deployment의 라벨과 일치해야 합니다
  ports:
    - port: 5000        # 서비스의 포트
      targetPort: 5000  # 컨테이너의 포트
      nodePort: 30500   # 외부에서 접근할 포트 (30000-32767 범위)